### ISSUE TITLE
Add repo shortname to each of the kabanero stack arrays

### ISSUE THREAD

**Issue by s1cyan** [kabanero-io/kabanero-command-line-services#159]
Currently the curated stacks have `reponame` in the `versions` json of the `curated stacks`. 
Though it will be repetitive, having the shortname in each of the stacks in new/kabanero/activated/obsolete will be easier for the console/cli to see the relationship of where the kab stack is from for displaying/filtering. 

currently just curated stacks have:
```
"curated stacks": [
    {
      "name": "java-microprofile",
      "versions": [
        {
          "images": [
            {
              "image": "docker.io/kabanero/java-microprofile:0.2.26"
            }
          ],
          "**reponame**": "incubator",
          "version": "0.2.26"
        }
      ]
    },

``` 

add the reponame to all the other stack arrays. This will be helpful for the console to create a filter on the stacks based on repo source.

**Comment by davco01a** [comment]
where are we supposed to get the correlated reponame from? It’s not in the metadata of the Kabanero stack instance, you want to just cross reference from the repo info that was gathered from the stack hub index? If so we won’t be able to get that info for an obsolete stack since by definition it will no longer be in the stack index.

**Comment by davco01a** [comment]
How urgent is this?

**Comment by davco01a** [comment]
merged: https://github.com/kabanero-io/kabanero-command-line-services/pull/166
