### ISSUE TITLE
Rest API to support Devfiles

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-command-line-services#184]
Transition the CLI service code to read from devFiles instead of stack indexes.

The stack hub team is still designing how they will provide transitional files to handle the change.

**Comment by davco01a** [comment]
Spoke to @deboer-tim 

e.g.

https://github.com/elsony/devfile-registry/tree/master/devfiles

**Comment by davco01a** [comment]
![image](https://user-images.githubusercontent.com/7747967/80817765-0f8abc00-8ba0-11ea-8922-7408365b7e78.png)

**Comment by davco01a** [comment]
Tim deBoer  11:45 AM
it's the interim phase we still need to discuss, b/c we plan to support both Appsody and odo in 3Q. I think Steve and Alan have agreed that we only need to support one at a time, but that either means you have code that'll do it both ways, or we add a little more info into our current hub so that you could switch to the json index all the time

**Comment by davco01a** [comment]
This will be handled under the GO rewrite.

At this last design meeting it was determined that we won't be reading from devfiles at all

closing

We will be supporting Appsody using the old Java CLI service and ODO with the new GO rewrite
